### ISSUE TITLE
A (unbalanced) double quote in the input hangs the online interpreter

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#10]
Right now if I type a double quote in the input area and append an arbitrary letter to it, and use arbitrary single letter command as the code, the online interpreter would hang. Explicitly suppressing implicit eval provides a workaround to the issue.

**Comment by tomtheisen** [comment]
That's a bug!  Here's a fix.  1ed459012673a9975bc0d7c4c70c30621e769c27
