### ISSUE TITLE
No comments??

### ISSUE THREAD

**Issue by vikramdurai** [tomtheisen/stax#11]
^ there doesn't seem to be any comments in the code..

**Comment by tomtheisen** [comment]
In ascii mode, you can make a comment using a tab character.  You can insert one in the web environment with `ctrl + I`.

[For example.](https://staxlang.xyz/#c=A%09the+value+ten%0Am%09map,+then+output%0AJ%09square&i=&a=1)

**Comment by vikramdurai** [comment]
I meant in the source code for the interpreter/compiler (this is open source man)

**Comment by vikramkhalsa** [comment]
I agree. Need more comments!

**Comment by tomtheisen** [comment]
PRs welcome.  I'm closing this.
