### ISSUE TITLE
Feature request: Base64 encode/decode

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#13]
When a string literal containing Unicode characters has to be used, the whole Stax program cannot be packed no matter how long it is. There are many solutions to this. Adding Base64 encode/decode is just one of them.

**Comment by tomtheisen** [comment]
I think this is inspired by the Chinese multiplication table challenge.  Stax does seem lacking in this area.  I will give some thought to the best approach.  Base-95 would pack more tightly, but base64 is likely to come up elsewhere.  But base-94 wouldn't need to escape double quotes.  Hmm... 

In any case, I will definitely improve this area somehow.

**Comment by tomtheisen** [comment]
I've fleshed out an integer array encoding scheme.  It's in the future branch at the moment.  It's implemented in C#, and outlined [here](https://github.com/tomtheisen/stax/blob/future/docs/compressed.md#crammed-integer-arrays).

**Comment by tomtheisen** [comment]
I made a base64 [encode](https://staxlang.xyz/#c=%7B2%7CE8%29m%7B%2BkVAVaVd.%2B%2F%2B%2B%2B%7E6%2F%7B6%282%7CE%3B%40m+c%25N4%25%27%3D*%2B,d&i=Man+is+distinguished,+not+only+by+his+reason,+but+by+this+singular+passion+from+other+animals,+which+is+a+lust+of+the+mind,+that+by+a+perseverance+of+delight+in+the+continued+and+indefatigable+generation+of+knowledge,+exceeds+the+short+vehemence+of+any+carnal+pleasure.&a=1) and [decode](https://staxlang.xyz/#c=%7EVAVaVd.%2B%2F%2B%2B%2B%3B%7B[I2%7CE6%29m%7B%2Bk,%27%3D%238*T8%2F%7B2%7CEm&i=TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCBieSB0aGlzIHNpbmd1bGFyIHBhc3Npb24gZnJvbSBvdGhlciBhbmltYWxzLCB3aGljaCBpcyBhIGx1c3Qgb2YgdGhlIG1pbmQsIHRoYXQgYnkgYSBwZXJzZXZlcmFuY2Ugb2YgZGVsaWdodCBpbiB0aGUgY29udGludWVkIGFuZCBpbmRlZmF0aWdhYmxlIGdlbmVyYXRpb24gb2Yga25vd2xlZGdlLCBleGNlZWRzIHRoZSBzaG9ydCB2ZWhlbWVuY2Ugb2YgYW55IGNhcm5hbCBwbGVhc3VyZS4%3D%0A&a=1) suitable for including in stax as a `:`-prefixed macro.  But I think I'm not going to do it.  This implementation operates on bytes, which are just numbers [0 .. 255] in stax, so it's suitable for encoding ascii strings, but those are better as plain literals anyway.  Strings in stax are arrays of codepoints, so any strings with codepoints out of the byte range aren't going to be able to decoded this way.
