### ISSUE TITLE
Can't push 10

### ISSUE THREAD

**Issue by GolfingSuccess** [tomtheisen/stax#15]
`10` pushes `0` instead.

**Comment by tomtheisen** [comment]
Like the [docs](https://github.com/tomtheisen/stax/blob/master/docs/instructions.md#numerics) say, 10 is `A` in stax.  `10` pushes 1 and 0 separately.

**Comment by GolfingSuccess** [comment]
Ah, so it's actually a golfing feature? Clever. The docs are pretty large to search for "10". 😛

**Comment by tomtheisen** [comment]
Yeah, it's not the most obvious thing.  The instruction page needs a re-org, but I haven't figured out what to do yet.
