### ISSUE TITLE
|l doesn't work for cases with multiple zeros

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#17]
Illustrated [here](https://staxlang.xyz/#c=%7Cl&i=[0+3]%0A[3+0]%0A[0+0]%0A[0+0+3]%0A[3+0+0]%0A[0+3+0]&a=1&m=2). Only the first and the second inputs works correctly. According to Mathematica and others, all of them should return `0`.

**Comment by tomtheisen** [comment]
[Related](https://staxlang.xyz/#c=%7Cl&i=0+3%0A3+0%0A0+0&a=1&m=2)

**Comment by tomtheisen** [comment]
Fixed in c5914d9b4b26e3f7ab4226f19e83000def87c31f
