### ISSUE TITLE
|T has issues with large arrays

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#18]
See [this](https://staxlang.xyz/#c=VA20%282%7CTm&a=1) and [this](https://tio.run/##Ky5JrPj/P8zRyEDDqCYk9/9/AA) for examples. If we change `20` to `A` then it just runs fine. On the other hand, [this](https://staxlang.xyz/#c=VA20%28%3A2m&a=1) works as well.

**Comment by tomtheisen** [comment]
Thanks for the report.  It was an integer overflow bug.  Fixed in 6d6bcaa40053292d678a18f422fcaace9c50283b.

I will be releasing 1.0.7 in the next two days if I have time.
