### ISSUE TITLE
|b doesn't work for negative numbers

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#19]
[Here](https://staxlang.xyz/#c=3%7Cb&i=-14&a=1) is a repro.

**Comment by tomtheisen** [comment]
Should the correct result be "-112" in that case?  It's what I'd assume, and it seems to make sense.

**Comment by William8915** [comment]
Yes, I assume so.

**Comment by tomtheisen** [comment]
Added in 59521baffe8fdbadd989bb982653e9c8528b447c
