### ISSUE TITLE
Multiple issues in spec with &

### ISSUE THREAD

**Issue by joshudson** [tomtheisen/stax#22]
& arr int any conflicts with & arr int block

& arr arr any conflicts with & arr arr block

When & arr int any gets a negative integer bigger than array's size the program's behavior is unspecified.  arr int int any form excludes negative indices so the problem does not occur.

**Comment by tomtheisen** [comment]
I will do something to address this conflicts.  It will probably consist exclusively of documentation changes.

**Comment by tomtheisen** [comment]
80d341be5000b92665db331fbfc67aa651b55a01
