### ISSUE TITLE
Annoying behaviour of Escape key in web environment with Quick Reference bar

### ISSUE THREAD

**Issue by TheWastl** [tomtheisen/stax#23]
If I press Esc to abort a program while the Quick Reference bar is open, it closes the Quick Reference bar. While there is another way to close the Quick Reference bar (F1), I haven't found another way to abort the program without clicking the button. It overrides the only and documented way to abort the program by an undocumented second way to close the Quick Reference bar, which is quite annoying.

**Comment by tomtheisen** [comment]
Good point.  This is an unnecessary usability problem.  There's a simple fix, so I'll address this.

I've been less active, because I have a new newborn in the house, but I will take a look when I get a chance.

**Comment by tomtheisen** [comment]
I prioritized program cancellation over quickref closing when both are active in c65daf9acf2fdb9cddd117058a397e4aebe40de7.  It will be in the next release.
