### ISSUE TITLE
Incorrect diagnostic for :[

### ISSUE THREAD

**Issue by joshudson** [tomtheisen/stax#27]
On staxlang.xyz

Code: `{}"a":[`

Expected: Stax runtime error: macro not found for types in :[
Actual: Stax runtime error: macro not found for types in [

I spent an hour tracking this down because I couldn't figure out what instruction was faulting.

**Comment by tomtheisen** [comment]
Confirmed.

**Comment by tomtheisen** [comment]
Fixed in 9403fb711ba324f2fe63e84507ba7380b6f4e0f5
