### ISSUE TITLE
D instruction changes everything

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#3]
From [this online run](http://stax.tomtheisen.com/#c=%3BYD%7C%60&i=%5B1%2C2%5D&a=1) it can be seen that `D` is changing the main stack, the input stack, and the X  and Y variables. This behavior is undocumented and either this is a bug or the documentation is incomplete.

**Comment by tomtheisen** [comment]
Thanks for the bug report.  As luck would have it, I discovered this same issue earlier today.  It's fixed here https://github.com/tomtheisen/stax/commit/b139dd2fa49d1a670c4f562e5cd44199cfb43091#diff-5afd71dc45cf12e6db89032342ddf4c8L449

It's deployed now.

http://stax.tomtheisen.com/#c=cDPP&i=abc&a=1

**Comment by William8915** [comment]
Well, maybe I should do a git pull first next time ...
