### ISSUE TITLE
|b is a string operation

### ISSUE THREAD

**Issue by khuldraeseth** [tomtheisen/stax#30]
It'll therefore treat any zero as 32. [Not very nice](https://staxlang.xyz/#c=%7CB&i=[1,0,1,0]&a=1).

**Comment by khuldraeseth** [comment]
Looked over the code a bit. It's either this or negatives, looks like.

**Comment by khuldraeseth** [comment]
Whoops. It didn't occur to me that it's intended for use on strings.

**Comment by khuldraeseth** [comment]
"It's not a bug, it's a feature!"

**Comment by tomtheisen** [comment]
I'm glad you figured it out.  On the other hand, if you have an array of bits, you can use `:b`.

https://staxlang.xyz/#c=%3Ab&i=[1,0,1,0]&a=1
