### ISSUE TITLE
Feature request: Date & Time functions

### ISSUE THREAD

**Issue by razetime** [tomtheisen/stax#36]
It would  be useful to have date and time returning variables/ function for those types of challenges.

For reference, I wanted to solve [this.](https://codegolf.stackexchange.com/questions/178003/encode-the-date-in-christmas-eve-format?rq=1)

**Comment by tomtheisen** [comment]
I've considered doing this a few times, but until now, I haven't added any non-determinism to the language.  

Some date functions would be possible without non-determinism, but this particular challenge requires a `now()`-like function, which

**Comment by razetime** [comment]
@tomtheisen Is there a place where I can ask some more questions about stax? Github issues doesn't seem like an appropriate place(unless you're not opposed to it).

**Comment by tomtheisen** [comment]
I had a chat stack exchange chat room for a while, but it got garbage collected due to disuse.  I don't really mind this, but maybe I should set up a discord thing or something?

**Comment by razetime** [comment]
@tomtheisen if you're on the CGCC discord server, we can definitely chat there. It's pretty vacant for discussion.

**Comment by tomtheisen** [comment]
Sounds good, but I didn't know there was one.  Where do I find it?
