### ISSUE TITLE
Generators: how to use non-shorthand mode?

### ISSUE THREAD

**Issue by razetime** [tomtheisen/stax#38]
I've made a generator which repeatedly run-length encodes an array for [this](https://codegolf.stackexchange.com/questions/128916/kolakoski-reduction?rq=1) here: https://staxlang.xyz/#c=%7B%7B3%3Cm%7CA_%251%3D%21*%7Dgf%3AG&i=[1,2,2,1,1,2,1,2,2,1,2,2,1,1,2,1,1]%0A&m=2

How do I prevent shorthand mode and make it push intermediate results to stack? I'm not sure how to do it from the tutorial.

**Comment by tomtheisen** [comment]
`{{3<m|A_%1=!*}{:Ggf`

The key is to terminate the generator block with the `g` token.

**Comment by tomtheisen** [comment]
The generator docs might be a tad thin.  Maybe I'll add some more examples.
