### ISSUE TITLE
Feature Request: change of rot13

### ISSUE THREAD

**Issue by razetime** [tomtheisen/stax#39]
Instead of rot13, I think it would be more useful to have a general caesar cipher with  `str num` as arguments.

**Comment by tomtheisen** [comment]
This would only affect letters, correct?

**Comment by razetime** [comment]
Yes, it would only affect letters.

**Comment by tomtheisen** [comment]
I haven't done a release in a while.  I'll put this in the next one and release it soon.

I'll leave this open until it's released.

**Comment by tomtheisen** [comment]
It's out in stax 1.1.10 now.

https://staxlang.xyz/#c=1%3A3&i=foo,+bar&a=1
