### ISSUE TITLE
:P and :p directly outputs

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#4]
Calling the `:P` and `:p` (and maybe others, I don't know) directly outputs the prime instead of putting it on the top of the main stack.

**Comment by William8915** [comment]
The issue is related to macros in shorthand mode.

**Comment by tomtheisen** [comment]
Confirmed.  https://staxlang.xyz/#c=%3Ap+%22foo%22&i=6&a=1

I think your analysis is correct.

**Comment by tomtheisen** [comment]
Fixed in d46785bd3b1324b1e2547f1e5fe7ab7744db3537 .

Rolled into 1.0.2 and deployed.  https://staxlang.xyz/
