### ISSUE TITLE
int-nth-root freezes with inputs of 1 and 0

### ISSUE THREAD

**Issue by razetime** [tomtheisen/stax#41]
[Here's where the bug is happening.](https://staxlang.xyz/#c=%7Cn%7Cgxs%7CN&i=4%0A49%0A125&m=2) It happens every single time the program is run with an input of 1. The debugger shows that the inputs are 1 and 0 on the stack.

The tab is also frozen and cannot be reloaded.

**Comment by tomtheisen** [comment]
Confirmed bug.

`|n|gxs1M|N` is a work-around for that program.

I'm not sure what the 0-th root is really supposed to be in general.  Infinity maybe?

**Comment by tomtheisen** [comment]
Well, I decided the nth root of `x` should be `x` for any `n < 1`.

**Comment by tomtheisen** [comment]
This will be in the next release.
