### ISSUE TITLE
Feature request: an instruction for generating random numbers

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#5]
Such a feature exist in many other stack-based golfing languages.

**Comment by tomtheisen** [comment]
I've certainly considered it before.  At some point, I made the choice not to put any non-determinism into stax.  This mostly means 1) no current date function and 2) no random numbers.

I may reconsider my stance on random numbers.  Dates would be a bigger undertaking if I add types for them, or if I create string formatting options for them.

**Comment by tomtheisen** [comment]
After some consideration, I have decided not to implement any random behavior in stax.  I have a personal distaste for any golf challenges that have randomness in their required behavior.  To me this opens logical loopholes in what the precise definition of random is.  How can you really prove that a program is random in the correct way in general?  This is somewhat of a philosophical point, and I understand that not everyone feels this way.  Nonetheless,  I'm not going to add any non-determinism for now.  

If stax ever gains more widespread adoption, and there is a consensus that lack of randomness is holding it back, I'll revisit the issue.
