### ISSUE TITLE
Instructions Missing Documentations

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#6]
Not long ago I wanted to do a matrix transpose. I searched the document but could not find an instruction to do that. I can't believe that it is not implemented in Stax, so I checked the source code and found the instruction I need. It's `M`. I think I am going to live with it if this is the only instruction missing in the document.

Just now I tried to do factorization of a composite number, and again find that there are no such instructions in the document. I looked into the source and found the instruction `|f`. I don't know how many more are missing and I suggest making a thorough semi-automatic check over the source code to ensure that all available instructions have been properly documented.

In addition, some spurious quotation marks in the "Constant" section of the document should be removed. I have seen a recent commit removing the quotes for `VI` and `Vi`, but the quotes for `Ve` should be removed as well, for example.

A final issue on the document is, the document does not say whether it is possible to have a fraction literal, or how to embed one in the code. I know that I can write it in the input as `a/b` but even this (albeit somehow obvious) is not documented as well.

That said, I think the documentation of Stax is already much better than that of many golfing languages I have seen. I just want to make it even better.

There is an extra issue which may just as well be submitted as a separate issue. The Javascript version of Stax hangs if I run `|f` on `2147483647`. It is a prime, but it is not too large and can be handled properly by a normal Javascript code that does not use the `bigInteger` type to factorize a composite number.

**Comment by tomtheisen** [comment]
Thanks for your in-depth analysis of these problems.

I made some specific documentation improvements in 6f3b919a1ff980335348f663d2d38f6ce659b5a4 and improved the factorization efficiency in 381092ee9376c153c4efa1efcc10f3b074947db0.  Your test case ran in 0.16s on this machine.  Subsequent executions run in 0.01s because it caches primes.

Your idea of an automated documentation check is a good one.  I'm not quite sure how to go about doing that, since most of the instructions are so overloaded.  `M` was already documented under conditional block invocation for example.

**Comment by tomtheisen** [comment]
I just fixed a typo I made in the previous commit.  Thanks for your kind words about the documentation.  It's a goal of mine to make stax approachable to learn.  Many golfing languages are rather opaque and hard to approach.

Regarding fraction literals, there was already a small example showing them used for input in the [execution documentation](https://github.com/tomtheisen/stax/blob/master/docs/execution.md#implicit-eval).  I added a section to the (rational documentation)[https://github.com/tomtheisen/stax/blob/master/docs/types.md#rationals] that clarifies that there are no rational literals per se, but shows how you can construct an arbitrary one succinctly.

At this time, I don't see any way of automating instruction documentation completeness, so I will mark this issue as closed.

**Comment by William8915** [comment]
I can't agree more with the first paragraph of your last comment. As for the (semi-)automatic checking process, I do have some ideas and may write a snippet to do the check when I have time. I will update and reopen the issue when that is done.

**Comment by tomtheisen** [comment]
Thanks for your (future) contribution.

**Comment by tomtheisen** [comment]
I think it would be useful to have an alternate document for instruction documentation.  One not indexed by purpose or category.  Instead, it would be indexed by symbol, then by operand type(s).  That organization might facilitate completeness checking.  Just a though.

**Comment by William8915** [comment]
Yes my script is based on that and it did find some problems:

 1. the documentation for `column-align` has broken markdown
 2. the constant `Vu` is documented but is not implemented in the Javascript version of Stax.

**Comment by tomtheisen** [comment]
b8129ed84e61898a6525a41626ed341558c020e6
