### ISSUE TITLE
`:M` does not do what is described in the document

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#8]
It instead finds one of the elements with the longest run. So [for input `[1,2,3,3,3,1,2,1,2,1]` it returns `3` instead of `1`](https://staxlang.xyz/#c=%3AM&i=%5B1%2C2%2C3%2C3%2C3%2C1%2C2%2C1%2C2%2C1%5D) because although `1` appears four times, `3` has the longest run of length 3. Not sure whether it's a bug with the program or an issue with the documentation.

**Comment by tomtheisen** [comment]
This is a bug.  It will be fixed in 1.0.5

**Comment by tomtheisen** [comment]
Fix in 5cacadf1cf546c9090d875d28b13a9894c0b4550 (and another bug regarding min and max of arrays of arrays)

**Comment by William8915** [comment]
Why so complicated? I had thought `|=H` would suffice ...

**Comment by tomtheisen** [comment]
No good reason.  Your approach is better and golfer.

**Comment by tomtheisen** [comment]
`|=H` does not do the right thing for [2,1,1,2].  `|=` produces modes in sorted order, but :M specifies that it produces the last mode to appear.
